Added Biometric Authentication
openMF/mifos-passcode pull request #60
Opened 2024-08-05 12:40 UTC by akashmeruva9

Fixes #Issue_Number

<table style="border: 1px solid black;">
            <tr>
                <td  style="border: 1px solid black ;">
                    <img src="https://github.com/user-attachments/assets/7b2d62bf-1d11-4495-8b84-84af921dd94d"   width="200">
                </td>
</table>

https://github.com/user-attachments/assets/aa8aae0c-7051-4e86-8627-9e1e22cc7845

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-08-08 16:06 UTC, PratyushSingh07 requested changes

2024-08-08 16:06 UTC, PratyushSingh07 commented on app/src/main/java/com/mifos/passcode/PassCodeActivity.kt
> +        Toast.makeText(this, "New Screen", Toast.LENGTH_SHORT).show()
remove toast

2024-08-08 16:06 UTC, PratyushSingh07 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    activity: AppCompatActivity
why are we passing it here

2024-08-08 16:06 UTC, PratyushSingh07 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    )
no need to print this

2024-08-08 16:06 UTC, PratyushSingh07 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    LaunchedEffect(biometricResult) {
why in launched effect ?

2024-08-08 16:08 UTC, PratyushSingh07 requested changes

2024-08-08 16:08 UTC, PratyushSingh07 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    val biometricResult by promptManager.promptResults.collectAsState(
collectAsStateWithLifeCycle() in place of collectAsState

2024-08-08 16:09 UTC, PratyushSingh07 commented
Also make sure to encrypt the password that the user enters @akashmeruva9

2024-08-09 12:31 UTC, akashmeruva9 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    LaunchedEffect(biometricResult) {
Here we are observing the biometric result, if the biometric result = Authentication.NotSet, then it launches the activity to enroll the biometrics.
We can use an if statement here, but this gets triggered on every recomposition.

2024-08-09 12:35 UTC, PratyushSingh07 requested changes

2024-08-09 12:36 UTC, PratyushSingh07 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    LaunchedEffect(biometricResult) {
what are the cases in which we can Authentication.NotSet as a result of `biometricResult`

2024-08-09 12:38 UTC, akashmeruva9 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    val biometricResult by promptManager.promptResults.collectAsState(
here biometric result is not a StateFLow intitially , so we have to initialize it with null here.

2024-08-09 12:46 UTC, akashmeruva9 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    LaunchedEffect(biometricResult) {
when this happens : 

BiometricManager.BIOMETRIC_ERROR_NONE_ENROLLED -> {
    resultChannel.trySend(BiometricResult.AuthenticationNotSet)
    return
}

2024-08-09 12:54 UTC, PratyushSingh07 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    activity: AppCompatActivity
use context or this to pass reference to an activity.  what you have done is not the solution

2024-08-09 13:50 UTC, akashmeruva9 commented on compose/src/main/java/com/mifos/compose/component/PassCodeScreen.kt
> +    LaunchedEffect(biometricResult) {
when we launch this
  
```
    LaunchedEffect(true){
        if(preferenceManager.hasPasscode) {
            promptManager.showBiometricPrompt(
                title = context.getString(R.string.biometric_auth_title),
                description = context.getString(R.string.biometric_auth_description)
            )
        }
    }
```


the biometric manager checks for fifferent conditions, 

```
    fun showBiometricPrompt(
        title: String,
        description: String
    ) {
        val manager = BiometricManager.from(activity)
        val authenticators = if(Build.VERSION.SDK_INT >= 30) {
            BIOMETRIC_STRONG or DEVICE_CREDENTIAL
        } else BIOMETRIC_STRONG

        val promptInfo = PromptInfo.Builder()
            .setTitle(title)
            .setDescription(description)
            .setAllowedAuthenticators(authenticators)

        if(Build.VERSION.SDK_INT < 30) {
            promptInfo.setNegativeButtonText("Cancel")
        }

        when(manager.canAuthenticate(authenticators)) {
            BiometricManager.BIOMETRIC_ERROR_HW_UNAVAILABLE -> {
                resultChannel.trySend(BiometricResult.HardwareUnavailable)
                return
            }
            BiometricManager.BIOMETRIC_ERROR_NO_HARDWARE -> {
                resultChannel.trySend(BiometricResult.FeatureUnavailable)
                return
            }
            BiometricManager.BIOMETRIC_ERROR_NONE_ENROLLED -> {
                resultChannel.trySend(BiometricResult.AuthenticationNotSet)
                return
            }
            else -> Unit
        }
```

then when this happens it updates the biometric result

```
BiometricManager.BIOMETRIC_ERROR_NONE_ENROLLED -> {
resultChannel.trySend(BiometricResult.AuthenticationNotSet)
return
}
```

2024-08-18 18:55 UTC, closed without merging